
name: 'mqbees'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'mqbees'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  mqbees:
    +schema: mqbees
    quran_text:
      +materialized: table
    quran_info:
      +materialized: table 

seeds:
  mqbees:
    quran_meta:
      +schema: meta
      +materialized: seed



vars:
  hizbs:   ['hizbs_meta','hizbs_temp_table']
  juzs:    ['juzs_meta','juzs_temp_table']
  manzils: ['manzils_meta','manzils_temp_table']
  pages:   ['pages_meta','pages_temp_table']
  rukus:   ['rukus_meta','rukus_temp_table']
  sajdas:  ['sajdas_meta','sajdas_temp_table']
  suras:   ['suras_meta','suras_temp_table']
  
  
  
  
  